version: "3"
services:
  pihole:
    image: pihole/pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9080:80/tcp"
      - "9443:443/tcp"
    cap_add:
      - NET_ADMIN
    environment:
      DNSMASQ_LISTENING: all
      ServerIP: 192.168.1.1
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.home.lab
      VIRTUAL_PORT: 9080
      WEBPASSWORD: pihole
      FTL_CMD: debug
    volumes:
      - /mnt/rpi-gfs/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /mnt/rpi-gfs/pihole/etc:/etc/pihole
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
