version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      ServerIP: "${IPADDR}"
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: "${DOMAIN}"
      VIRTUAL_PORT: 80
      WEBPASSWORD: "${PASSWD}"
      TZ: "${TIMEZONE}"
    extra_hosts:
      - "${DOMAIN}:${IPADDR}"
    volumes:
      - pihole:/etc/pihole
volumes:
    pihole:
      driver: local
      driver_opts:
        type: nfs
        o: "addr=${NFS_IPADDR},nolock,soft,rw"
        device: ":${NFS_MOUNT}"
